swiftlint_version: 0.55.1

excluded:
  - Pods
  - Carthage
  - DerivedData
  - "*Tests"
  - .scripts

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - unused_capture_list
  - inclusive_language

analyzer_rules:
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - direct_return
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count # Not available in Sonar-Swift plugin
  - fatal_error_message
  - file_name_no_space
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
#  - indentation_width # Not available in Sonar-Swift plugin
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
#  - no_magic_numbers
#  - one_declaration_per_file
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
#  - prefer_self_type_over_type_of_self # Not available in Sonar-Swift plugin
  - prefer_zero_over_explicit_init
  - private_outlet
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_arrow_whitespace
  - return_value_from_void_function
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: error

  disable_print:
    included: ".*\\.swift"
    name: "Print Usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "print statements are not allowed please use log or log_* statement"
    severity: warning

  dont_import_uikit:
    included: ".*(?i)(ViewModel|VM).swift"
    name: "UIKit in ViewModel"
    regex: "^import (UIKit)$"
    message: "Don't import UIKit in ViewModel"
    severity: warning

  commented_out_code:
    included: ".*\\.swift"
    excluded: ".*Test(s)?\\.swift"
    name: "Commented out code"
    regex: "(^\\/\\/\\s*(?!LearnConnect)(?!swiftlint)(\\.?([a-z])))"
    capture_group: 0
    match_kinds:
      - comment
    message: "Comment starting with lowercase letter - did you forget to delete old code?"
    severity: warning

  multiline_commented_code:
    included: ".*\\.swift"
    name: "Commented code"
    regex: '^\s*[a-z]'
    match_kinds: comment
    message: "Comment starting with lowercase letter - did you forget to delete old code?"
    severity: warning


attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

# Default Rules Config
blanket_disable_command: warning
block_based_kvo: warning
class_delegate_protocol: warning
closing_brace: warning
closure_parameter_position: warning
colon: warning
comma: warning
comment_spacing: warning
compiler_protocol_init: warning
computed_accessors_order: warning
control_statement: warning
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

deployment_target:
  iOS_deployment_target: 13.0
  severity: error

discouraged_direct_init: warning
duplicate_conditions: error
duplicate_enum_cases: error
duplicate_imports: error
duplicated_key_in_dictionary_literal: error
dynamic_inline: error
empty_enum_arguments: warning
empty_parameters: warning
empty_parentheses_with_trailing_closure: warning
file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

for_where: warning
force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 60

function_parameter_count: 
  warning: 5
  error: 8
  ignores_default_parameters: true

generic_type_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 20
    error: 1000
  unallowed_symbols_severity: error
  validates_start_with_lowercase: error

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - i
    - id
    - x
    - y
    - z
    - vc
    - nc
    - vm
    - c

implicit_getter: warning
invalid_swiftlint_command: error
is_disjoint: warning
large_tuple: 
  warning: 3
  error: 4

leading_whitespace: warning
legacy_cggeometry_functions: warning
legacy_constant: warning
legacy_constructor: warning
legacy_hashing: error
legacy_nsgeometry_functions: warning
legacy_random: warning
line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

mark: warning
multiple_closures_with_trailing_closure: warning
nesting:
  type_level:
    warning: 2
  function_level:
    warning: 2
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: false
  ignore_typealiases_and_associatedtypes: false

no_fallthrough_only: warning
no_space_in_method_call: error
non_optional_string_data_conversion: warning
ns_number_init_as_function_reference: error
nsobject_prefer_isequal: warning
opening_brace: warning
operator_whitespace: warning
orphaned_doc_comment: warning
private_over_fileprivate: warning
private_unit_test: 
  severity: warning
  
protocol_property_accessors_order: error
reduce_boolean: warning
redundant_discardable_let: warning
redundant_objc_attribute: error
redundant_optional_initialization: warning
redundant_set_access_control: warning
redundant_string_enum_value: error
redundant_void_return: warning
return_arrow_whitespace: warning
self_in_property_initialization: warning
shorthand_operator: error
statement_position: error
static_over_final_class: warning
superfluous_disable_command: warning
switch_case_alignment:
  severity: warning
  indented_cases: false
  ignore_one_liners: false

syntactic_sugar: error
todo: warning
trailing_comma: warning
trailing_newline: warning
trailing_semicolon: warning
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

type_body_length: 
  warning: 250
  error: 350

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 1000

unavailable_condition: warning
unneeded_break_in_switch: error
unneeded_override: warning
unneeded_synthesized_initializer: warning
unused_closure_parameter: warning
unused_control_flow_label: warning
unused_enumerated: warning
unused_optional_binding: warning
unused_setter_value: warning
valid_ibinspectable: warning
vertical_parameter_alignment: warning
vertical_whitespace:
  max_empty_lines: 2
  severity: warning

void_function_in_ternary: warning
void_return: warning
xctfail_message: warning


# Opt-in Rules Config
array_init: warning
closure_body_length:
  warning: 30
  error: 50

closure_end_indentation: warning
closure_spacing: warning
collection_alignment: 
  severity: warning
  align_colons: false

convenience_type: warning
direct_return: warning
discouraged_object_literal: 
  severity: error
  image_literal: true
  color_literal: true

empty_collection_literal: warning
empty_count: warning
empty_string: warning
enum_case_associated_values_count: 
  warning: 5
  error: 6

fatal_error_message: warning
file_name_no_space: error
first_where: warning
force_unwrapping: warning
identical_operands: error
implicit_return: warning
implicitly_unwrapped_optional: 
  severity: warning
  mode: all_except_iboutlets
  
last_where: warning
literal_expression_end_indentation: warning
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: false
  severity: warning

multiline_arguments_brackets: warning
multiline_function_chains: warning
multiline_literal_brackets: warning
multiline_parameters:
  allows_single_line: false
  severity: warning

multiline_parameters_brackets: warning
# no_magic_numbers: warning
# one_declaration_per_file: warning
operator_usage_whitespace: warning
pattern_matching_keywords: warning
# prefer_self_type_over_type_of_self: warning
prefer_zero_over_explicit_init: error
private_outlet: warning
redundant_nil_coalescing: error
redundant_self_in_closure: warning
redundant_type_annotation: warning
return_value_from_void_function: warning
sorted_first_last: warning
sorted_imports: 
  severity: warning
  grouping: names
  

toggle_bool: warning
trailing_closure: warning
unneeded_parentheses_in_closure_argument: warning
vertical_parameter_alignment_on_call: warning
vertical_whitespace_between_cases: warning
vertical_whitespace_closing_braces: error
vertical_whitespace_opening_braces: error
weak_delegate: warning
yoda_condition: warning
